-- CreateTable
CREATE TABLE `UserStats` (
    `userId` VARCHAR(191) NOT NULL,
    `averageScore` INTEGER NOT NULL DEFAULT 0,
    `averageAccuracy` DOUBLE NOT NULL DEFAULT 0,
    `playCountUnique` INTEGER NOT NULL DEFAULT 0,
    `SS` INTEGER NOT NULL DEFAULT 0,
    `S` INTEGER NOT NULL DEFAULT 0,
    `A` INTEGER NOT NULL DEFAULT 0,
    `B` INTEGER NOT NULL DEFAULT 0,
    `C` INTEGER NOT NULL DEFAULT 0,
    `D` INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (`userId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
